### ISSUE TITLE
Package not installing

### ISSUE THREAD

**Issue by AnonymusBadger** [claytonrcarter/tree-sitter-phpdoc#20]
Hi!
I wanted to check out this package, but it just doesn't seem to install properly.
I've followed the steps from the README.
It looks like it's not compiling and there's no `./node_modules/.bin` directory.
I've tried using `yarn` just to see if it fixes the problem, but no dice.

**Comment by mikehaertl** [comment]
Not sure what you try to achieve but this is a parser for tree-sitter. You can't use it standalone and also need tree-sitter installed.

The README is maybe a bit misleading in that regard.

**Comment by AnonymusBadger** [comment]
Hmm... It might be more complicated in my case.
I'm using tree-sitter as doom-emacs extension and somehow it did not occur to me that this might not work by just installing the npm package 😅.
So sorry for raising the issue, most likely this isn't a problem on your side.
Though since it's Emacs there must be a way to combine those two, just not sure yet how

**Comment by mikehaertl** [comment]
No worries. I can't help out with emacs though. In the case of neovim there's a dedicated plugin ([nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter))  that deals with integration of all the grammars. Maybe something like this also exists for Emacs?

Your issue also made me play with the npm package and I found some problems.

@claytonrcarter 
I found the README for the YAML grammar useful: https://github.com/ikatyang/tree-sitter-yaml.

So I tried the example they have (adapted to PHPDoc) - but it failed due to the old ABI version problem that I thought should already be fixed ("Incompatible language version. Compatible range: 13 - 13. Got: 12"). Then I found that you get an outdated version with npm install. So maybe we should bump the version first and see if this fixes the issue.

If things work out I could provide another PR to update the README.

**Comment by mikehaertl** [comment]
@AnonymusBadger From a quick search this is probably the right place where you could ask for inclusion of phpdoc: https://github.com/emacs-tree-sitter/tree-sitter-langs

**Comment by claytonrcarter** [comment]
I am also a (recent) doom emacs user and, to my dismay, my understanding is that Emacs tree-sitter [currently doesn't support multiple "languages" in a single file](https://github.com/emacs-tree-sitter/elisp-tree-sitter/discussions/211). So, @AnonymusBadger, you and I are both out of luck at this time. 😢 

Unrelated, but @mikehaertl, b/c my primary use case is no longer Atom, I'm intending to remove the silly "we gotta use an old version of tree-sitter" constraint from this package ... I just haven't gotten around to it yet.
