### ISSUE TITLE
Qualifed name starting with backslash not recognized

### ISSUE THREAD

**Issue by mikehaertl** [claytonrcarter/tree-sitter-phpdoc#3]
A fully qualified name can also start with a backslash.

![ts_phpdoc_backslash](https://user-images.githubusercontent.com/675062/149821462-a8f292c2-2fea-4202-b04d-bf9978a99715.png)

Even though they should not be strictly required they are not wrong either. In fact intelephense does not work well if I leave them away.

It also seems that if the namespace has more path components things break:

![ts_phpdoc_backslash2](https://user-images.githubusercontent.com/675062/149822348-1c99cbb2-8ed0-4ffa-be98-af26c2c85609.png)

**Comment by mikehaertl** [comment]
Everything's fine with `@param` and `@property`. Here a better example that shows several combinations:

![ts_phpdoc_type](https://user-images.githubusercontent.com/675062/149833569-f0b01ae0-c215-42f0-bf33-c1b4797222f4.png)

**Comment by claytonrcarter** [comment]
Thanks for the report. Confirmed. It seems that `@param` and `@property` are working properly b/c they require the variable to come between the type and description. Since `@return` doesn't have that requirement, the description is being greedy and consuming the last segment of the type. For whatever reason, if there is only whitespace between the type and the newline, it works OK.

**Comment by claytonrcarter** [comment]
Ah 🤦 I wasn't get PR emails for this. I see you already have a fix in place in #4
